#!/usr/bin/env node
'use strict';
/**
 * Produces dist/calculator-embed.html — one self-contained file you can paste
 * straight into a Wix HTML embed. The model is inlined from public/model.js so
 * there is still only one copy of the maths in the repo.
 *
 *   node scripts/build-embed.js [service-url]
 *   npm run build:embed
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const API = process.argv[2] || process.env.SERVICE_URL ||
  'https://scoothero-calculator.onrender.com';

const html = fs.readFileSync(path.join(ROOT, 'public', 'index.html'), 'utf8');
const model = fs.readFileSync(path.join(ROOT, 'public', 'model.js'), 'utf8');

const TAG = '<script src="model.js"></script>';
if (html.indexOf(TAG) === -1) {
  console.error('Could not find the model.js script tag in public/index.html — aborting.');
  process.exit(1);
}

const banner =
  '<!-- ScootHero fleet calculator — self-contained build.\n' +
  '     Generated ' + new Date().toISOString().slice(0, 10) + ' by scripts/build-embed.js.\n' +
  '     Edit public/index.html or public/model.js and rebuild; do not edit this file. -->\n';

const inlined =
  '<script>\n/* --- model.js (inlined) --- */\n' + model + '\n</script>\n' +
  '<script>window.SH_API = ' + JSON.stringify(API) + ';</script>';

const out = banner + html.replace(TAG, inlined);

const dist = path.join(ROOT, 'dist');
fs.mkdirSync(dist, { recursive: true });
const file = path.join(dist, 'calculator-embed.html');
fs.writeFileSync(file, out);

console.log('Wrote ' + path.relative(ROOT, file));
console.log('  size:      ' + (out.length / 1024).toFixed(1) + ' KB');
console.log('  posts to:  ' + API);
console.log('\nRemember: add the page origin to ALLOWED_ORIGINS on the service,');
console.log('otherwise the browser will block the request.');
